#!/usr/bin/env bash
#task 1
What type of network a computer in local is connected?
["2"]
What type of newtwork could connected an office in one building to another office in a building
a few streets away?
["2"]
What network do you use when you browse www.google.com from your smartphone(not connected to the Wifi)?
["2"]
